### ISSUE TITLE
Error code 101

### ISSUE THREAD

**Issue by pollocluck** [WiIIiam278/breaking-bad-ds#7]
I downloaded the rom from the website today and tried to run the game on my DS lite with the R4 card. The error I'm getting is this:

`File /bgm/title_hook.raw not found.
Error code 101.`

In [the video](https://youtu.be/HiiZxOU934E?si=Mz2lbTBu_S5Em1Xx), it shows the dev playing the game on a pink DS Lite, so I'm confused as to why it's not working on mine.

**Comment by WiIIiam278** [comment]
Hi,
Please update the kernel installed on your flash cart, as this is the source of this error. Try installing twilight menu on it :)

**Comment by pollocluck** [comment]
> Hi, Please update the kernel installed on your flash cart, as this is the source of this error. Try installing twilight menu on it :)

I did that today through [this website](https://www.r43ds.org/pages/R4-3DS-Gold-Pro-Firmware.html), but I still got the same error. I also saw that the Twilight menu is mainly meant for DSi and 3DS flash carts, but is it _required_ to play the game on original hardware?

**Comment by WiIIiam278** [comment]
It shouldn't be, but this error is indicative that your particular flashcart firmware isn't compatible with libfat

**Comment by pollocluck** [comment]
Ah ok, I'll try to experiment with Twilight on my cart later this week. Thanks for the info and suggestion!

**Comment by WiIIiam278** [comment]
Closing this as it is indeed a flashcart hardware issue typically, nothing I can really do :)
